### ISSUE TITLE
Dependent Queries on uid using useFirestoreDocument hook 

### ISSUE THREAD

**Issue by catdoglt** [invertase/react-query-firebase#18]
I am trying to pass user uid from **useAuthUser** hook to my useFirestoreDocument.

However,

```
const user = useAuthUser(["user"], auth);
const ref = doc(firestore, "users", user.data.uid);
```

Does not work because user is originally initialized as undefined, before it is populated and you get error.

In React-Query there is an optional field **enabled** that can pause the query until it's ready to be executed https://react-query.tanstack.com/guides/dependent-queries

Can this be done with react-query-firebase hooks as well?

**Comment by kabtamu-degifie** [comment]
The issues regarding infinite loading and disabled functionality associated with the useFirestoreDocumentData hook have been resolved. Therefore, we can now utilize it with Next.js versions 13 or 14. 
 https://github.com/invertase/react-query-firebase/pull/97
