### ISSUE TITLE
Does it possible to add React 16.14 support?

### ISSUE THREAD

**Issue by vomchik** [invertase/react-query-firebase#19]
Does it possible to add React 16.14 support?

```js
"peerDependencies": {
  "react": ">=16.14 || >=17"
 },
```

**Comment by Ehesp** [comment]
Hm it should do yeah, I guess it should support whatever react query supports. Will look into it tomorrow.

You could always use patch package as a quick workaround.

**Comment by Ehesp** [comment]
React Query support is

"react": "^16.8.0 || ^17.0.0"

**Comment by vomchik** [comment]
> React Query support is
> 
> "react": "^16.8.0 || ^17.0.0"

![CleanShot 2021-11-05 at 14 56 58@2x](https://user-images.githubusercontent.com/732085/140513665-a50cef99-bea3-419e-94a9-9b94bd282e5f.png)
Looks like we need to add the same to your lib

**Comment by vomchik** [comment]
> Hm it should do yeah, I guess it should support whatever react query supports. Will look into it tomorrow.
> 
> You could always use patch package as a quick workaround.

as far I know we can't use  https://www.npmjs.com/package/patch-package for patching a package.json file.

**Comment by vomchik** [comment]
@Ehesp any news?

**Comment by Salakar** [comment]
> @Ehesp any news?

If you can send a PR that will be helpful

**Comment by vomchik** [comment]
@Salakar  https://github.com/invertase/react-query-firebase/pull/20 please look when you have a time

**Comment by Ehesp** [comment]
Cheers all published.
