### ISSUE TITLE
How to query array of references

### ISSUE THREAD

**Issue by julianklumpers** [invertase/react-query-firebase#24]
Hi, first I want to say thank you for making this awesome symbiosis of react-query and Firebase.

I was wondering how to approach to query an array of references.
For example, my data looks like this:

```js
{
  email: "Weston_Hauck@hotmail.com"
  locations: [Ec2, Ec2, Ec2]
  roles: (3) ['master', 'manager', 'scout']
  username: "Winona14"
}
```
Here, "locations" is an array of Firebase references.
What would be the best approach to fetch those references? Since the hooks don't support array of docs.
Something like this would be great, under the hood it could use something like `useQueries` from 'react-query'

```js
  const { data: locations, loading, error } = useFirestoreDocumentData<any>(
    ['locations', auth.uid],
    user.locations.map(location => doc(FireBase.db, location.path)),
    {},
    { enabled: Boolean(auth.uid) },
  );
```

if there is no way to do this currently, I will try to make a PR to support to fetch arrays of `docs`

Thank you

**Comment by Ehesp** [comment]
Hmm interesting one... I suspect something like this is possible, although I haven't tried it yet:

```js
  const query = useFirestoreDocumentData<any>(
    ['locations', auth.uid],
    doc(db, 'path to document'),
    {},
    { enabled: Boolean(auth.uid) },
  );

const docs = query.isSuccess ? query.data.locations.map(l => doc(db, location.path)) : [];

const locations = useQueries(docs.map((doc) => {
  return useFirestoreDocumentData(['locations', 'auth.uid', doc.path, doc, {}, {
    enabled: query.isSuccess,
  }]);
});
```

So get the document first, then load the locations when the document has returned them?

**Comment by Ehesp** [comment]
Let me know how you get on, I do think that logic should be ok - if not, I'll try and think of something else.

**Comment by julianklumpers** [comment]
It throws React hook order error. [Link to docs](https://reactjs.org/docs/hooks-rules.html#only-call-hooks-at-the-top-level)
I tinkered around and made something that works based on the source code from `useFirestoreDocumentData ` i can make a PR if you like?

**Comment by Ehesp** [comment]
Yeah for sure send up a PR, even if it's a rough idea I can take a look.

Pretty open to ideas, fairly new library so there's for sure room for improvement.

**Comment by ifours** [comment]
@julianklumpers as an alternative, you can create a regular firestore `query` with [document id sentinel](https://firebase.google.com/docs/reference/js/firestore_.md#documentid). For example:

```
query(collection('locations'), where(documentId(), 'in', data.locations.map(doc => doc.id)))
```

**Comment by julianklumpers** [comment]
@ifours wow! Did not know about this sentinel, thanks for pointing that out for me! Really appreciate it.
