### ISSUE TITLE
Discussion: production readiness

### ISSUE THREAD

**Issue by atanaskanchev** [invertase/react-query-firebase#34]
Hi, first I would like to thank you for this amazing library, I am planning to use it for a production app that will be launching soon. I am a bit worried if the lib is production ready. Anyone willing to share their experience using it in prod? My concerns are mainly related to any unexpected Firebase charges, especially in the current state of lib, where to make the real time query work we needed to set the cacheTime: 0

```javascript 
new QueryClient({
        defaultOptions: {
          queries: {
            retry: 3,
            retryDelay: (attemptIndex) => Math.min(1000 * 2 ** attemptIndex, 30000),
            staleTime: 10 * 60 * 1000, // 10 min
            cacheTime: 0, // 5 min (default)
            refetchOnWindowFocus: false
          }
        }
      })
```

Also it seems that there's some stale issues, is the lib looking for maintainers?

**Comment by Ehesp** [comment]
Sorry I've been sat on some code changes for a while and got distracted with other stuff.

https://github.com/invertase/react-query-firebase/pull/35

I've not tested this (code wise) yet, however based on my initial experiments in a playground environment it seems to be working ok, I'm just weary there may be scenarios that I haven't thought about.

**Comment by atanaskanchev** [comment]
Unfortunately it seems this library is no longer supported.

**Comment by Ehesp** [comment]
We've just got no resource to work on it right now I'm afraid.
